### ISSUE TITLE
fontbakery style name failure

### ISSUE THREAD

**Issue by liamspradlin** [liamspradlin/Girassol-Display#5]
> Checking file is named canonically.
>  * FAIL: Style name used in "/Girassol-Display.ttf" is not canonical. You should rebuild the font using any of the following style names: "Thin", "ExtraLight", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black", "Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium Italic", "SemiBold Italic", "Bold Italic", "ExtraBold Italic", "Black Italic". [code: bad-static-filename]
> 
>    Result: FAIL

Encountering this failure when I run fontbakery, but the Style name _is_ set to "Regular" in the Font Info before the font is built.

**Comment by thundernixon** [comment]
Have you tried changing the file name to `Girassol-Regular.ufo`, then building? Potentially, you may even pass this test by just changing the file name of the output font to `Girassol-Regular.ttf`. Let me know if that changes anything!

**Comment by liamspradlin** [comment]
I can't believe it, building it as Girassol-Regular worked! 🎉
