### ISSUE TITLE
Google Fonts QA report

### ISSUE THREAD

**Issue by m4rc1e** [liamspradlin/Girassol-Display#6]
## Fontbakery report

Fontbakery version: 0.7.15

<details>
<summary><b>[8] Girassol-Regular.ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)

* ⚠ **WARN** OS/2 VendorID value 'LIAM' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
<pre>--- Rationale ---

Even though the OpenType spec allows unitsPerEm to be any value between 16 and
16384, the Google Fonts project aims at a narrower set of reasonable values.

The spec suggests usage of powers of two in order to get some performance
improvements on legacy renderers, so those values are acceptable.

But value of 500 or 1000 are also acceptable, with the added benefit that it
makes upm math easier for designers, while the performance hit of not using a
power of two is most likely negligible nowadays.

Another acceptable value is 2000. Since TT outlines are all integers (no
floats), then instances in a VF suffer rounding compromises, and therefore a
1000 UPM is to small because it forces too many such compromises.

Therefore 2000 is a good &#x27;new VF standard&#x27;, because 2000 is a simple 2x
conversion from existing fonts drawn on a 1000 UPM, and anyone who knows what
10 units can do for 1000 UPM will know what 20 units does too.

Additionally, values above 2048 would result in filesize increases with not
much added benefit.

</pre>

* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations. [code: legacy-value]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---

Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will
only differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.

However, a quotedbl should have 2 contours, unless the font belongs to a
display family.

This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.

</pre>

* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: Q	Contours detected: 3	Expected: 2
Glyph name: e	Contours detected: 1	Expected: 2
Glyph name: g	Contours detected: 1	Expected: 2 or 3
Glyph name: i	Contours detected: 1	Expected: 2
Glyph name: j	Contours detected: 1	Expected: 2
Glyph name: p	Contours detected: 1	Expected: 2
Glyph name: q	Contours detected: 3	Expected: 2
Glyph name: ae	Contours detected: 2	Expected: 3
Glyph name: egrave	Contours detected: 2	Expected: 3
Glyph name: eacute	Contours detected: 2	Expected: 3
Glyph name: ecircumflex	Contours detected: 2	Expected: 3
Glyph name: edieresis	Contours detected: 3	Expected: 4
Glyph name: thorn	Contours detected: 1	Expected: 2
Glyph name: emacron	Contours detected: 2	Expected: 3
Glyph name: ebreve	Contours detected: 2	Expected: 3
Glyph name: edotaccent	Contours detected: 2	Expected: 3
Glyph name: eogonek	Contours detected: 1	Expected: 2
Glyph name: ecaron	Contours detected: 2	Expected: 3
Glyph name: gcircumflex	Contours detected: 2	Expected: 3 or 4
Glyph name: gbreve	Contours detected: 2	Expected: 3 or 4
Glyph name: gdotaccent	Contours detected: 2	Expected: 3 or 4
Glyph name: gcommaaccent	Contours detected: 2	Expected: 3 or 4
Glyph name: hbar	Contours detected: 2	Expected: 1
Glyph name: iogonek	Contours detected: 1	Expected: 2 or 3
Glyph name: oe	Contours detected: 2	Expected: 3
Glyph name: Racute	Contours detected: 2	Expected: 3
Glyph name: Rcommaaccent	Contours detected: 2	Expected: 3
Glyph name: Rcaron	Contours detected: 2	Expected: 3
Glyph name: aeacute	Contours detected: 3	Expected: 4
Glyph name: etilde	Contours detected: 2	Expected: 3
Glyph name: thorn	Contours detected: 1	Expected: 2
Glyph name: eacute	Contours detected: 2	Expected: 3
Glyph name: Q	Contours detected: 3	Expected: 2
Glyph name: ebreve	Contours detected: 2	Expected: 3
Glyph name: Rcaron	Contours detected: 2	Expected: 3
Glyph name: p	Contours detected: 1	Expected: 2
Glyph name: e	Contours detected: 1	Expected: 2
Glyph name: q	Contours detected: 3	Expected: 2
Glyph name: ae	Contours detected: 2	Expected: 3
Glyph name: Racute	Contours detected: 2	Expected: 3
Glyph name: j	Contours detected: 1	Expected: 2
Glyph name: gcircumflex	Contours detected: 2	Expected: 3 or 4
Glyph name: eogonek	Contours detected: 1	Expected: 2
Glyph name: aeacute	Contours detected: 3	Expected: 4
Glyph name: gbreve	Contours detected: 2	Expected: 3 or 4
Glyph name: edotaccent	Contours detected: 2	Expected: 3
Glyph name: g	Contours detected: 1	Expected: 2 or 3
Glyph name: oe	Contours detected: 2	Expected: 3
Glyph name: ecaron	Contours detected: 2	Expected: 3
Glyph name: edieresis	Contours detected: 3	Expected: 4
Glyph name: ecircumflex	Contours detected: 2	Expected: 3
Glyph name: i	Contours detected: 1	Expected: 2
Glyph name: emacron	Contours detected: 2	Expected: 3
Glyph name: gdotaccent	Contours detected: 2	Expected: 3 or 4
Glyph name: hbar	Contours detected: 2	Expected: 1
Glyph name: egrave	Contours detected: 2	Expected: 3
Glyph name: iogonek	Contours detected: 1	Expected: 2 or 3 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check name table: FULL_FONT_NAME entries.</summary>

* [com.google.fonts/check/name/fullfontname](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/fullfontname)

* ⚠ **WARN** Entry [FULL_FONT_NAME(4):MACINTOSH(1)] on the "name" table: Got "Girassol" which lacks "Regular", but it is probably OK in this case. [code: lacks-regular]
* ⚠ **WARN** Entry [FULL_FONT_NAME(4):WINDOWS(3)] on the "name" table: Got "Girassol" which lacks "Regular", but it is probably OK in this case. [code: lacks-regular]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
<pre>--- Rationale ---

All ligatures in a font must have corresponding caret (text cursor) positions
defined in the GDEF table, otherwhise, users may experience issues with caret
rendering.

</pre>

* ⚠ **WARN** GDEF table is missing, but it is mandatory to declare it on fonts that provide ligature glyphs because the caret (text cursor) positioning for each ligature must be provided in this table. [code: GDEF-missing]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).

</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- R + R
	- T + T
	- r + r
	- t + t

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking Vertical Metric Linegaps.</summary>

* [com.google.fonts/check/linegaps](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hhea.html#com.google.fonts/check/linegaps)

* ⚠ **WARN** hhea lineGap is not equal to 0. [code: hhea]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check for points out of bounds.</summary>

* [com.google.fonts/check/points_out_of_bounds](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/glyf.html#com.google.fonts/check/points_out_of_bounds)

* ⚠ **WARN** The following glyphs have coordinates which are out of bounds:
	* ('Adieresis', 140, 919)
	* ('Adieresis', 291, 919)
	* ('Cdotaccent', 225, 919)
	* ('Edieresis', 131, 919)
	* ('Edieresis', 282, 919)
	* ('Edotaccent', 220, 919)
	* ('Gdotaccent', 215, 919)
	* ('Idieresis', 47, 919)
	* ('Idieresis', 198, 919)
	* ('Idotaccent', 125, 919) and 79 more.

This happens a lot when points are not extremes, which is usually bad. However, fixing this alert by adding points on extremes may do more harm than good, especially with italics, calligraphic-script, handwriting, rounded and other fonts. So it is common to ignore this message. [code: points-out-of-bounds]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 8 | 72 | 7 | 74 | 0 |
| 0% | 0% | 5% | 45% | 4% | 46% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

## Diff images: [girassol_qa.zip](http://35.188.158.120/media/63b726d5-8f9f-4081-beb6-50ec99c377f9/girassol_qa.zip)

**Comment by m4rc1e** [comment]
Very clean. 

Would you mind dropping the reserved font name?

cc @davelab6

**Comment by liamspradlin** [comment]
Thank you, Marc! To make sure I'm interpreting your question correctly - should I remove the RFN from the top of my OFL.txt?

**Comment by davelab6** [comment]
Correct :) This is mentioned on
https://github.com/google/fonts/blob/master/CONTRIBUTING.md

**Comment by liamspradlin** [comment]
Ah, my mistake. I guess I interpreted that bullet point as an informative statement 😅

OFL.txt has now been updated.

**Comment by davelab6** [comment]
The only WARN that seems actionable is the vertical metrics...

**Comment by liamspradlin** [comment]
Just made an update - linegaps check is now passing on my machine!

**Comment by davelab6** [comment]
Excellent!
